'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowLeft, ArrowRight, BookOpen, Building2, CalendarDays, Check, Clock3, Code2, Dumbbell, Mail, Scale, ShieldCheck, Stethoscope, Users } from 'lucide-react';
import { SiteShell } from '../../core/layout';
import { Button, Card, DetailPanel, ItemGrid, MediaFrame, SectionHeading, StatStrip } from '../../core/ui';
import { lawFirmData } from '../../content/law';
import { saasPlatformData } from '../../content/saas';
import { dentalClinicData } from '../../content/dental';
import { fitnessClubData } from '../../content/fitness';

type SiteId = 'law' | 'saas' | 'dental' | 'fitness';

const NAV: Record<SiteId, Array<{ label: string; href: string }>> = {
  law: [{ label: 'Bakış', href: '/sites/law/index/' }, { label: 'Uzmanlıklar', href: '/sites/law/practices/' }, { label: 'Ekip', href: '/sites/law/team/' }, { label: 'Yayınlar', href: '/sites/law/publications/' }, { label: 'İletişim', href: '/sites/law/contact/' }],
  saas: [{ label: 'Ürün', href: '/sites/saas/index/' }, { label: 'Modüller', href: '/sites/saas/product/' }, { label: 'Çözümler', href: '/sites/saas/solutions/' }, { label: 'Fiyatlandırma', href: '/sites/saas/pricing/' }, { label: 'Güncellemeler', href: '/sites/saas/changelog/' }, { label: 'Dokümanlar', href: '/sites/saas/docs/' }],
  dental: [{ label: 'Klinik', href: '/sites/dental/index/' }, { label: 'Tedaviler', href: '/sites/dental/treatments/' }, { label: 'Hekimler', href: '/sites/dental/clinicians/' }, { label: 'Teknoloji', href: '/sites/dental/technology/' }, { label: 'Hasta rehberi', href: '/sites/dental/patient-guide/' }],
  fitness: [{ label: 'Kulüp', href: '/sites/fitness/index/' }, { label: 'Programlar', href: '/sites/fitness/programs/' }, { label: 'Koçlar', href: '/sites/fitness/coaches/' }, { label: 'Tesisler', href: '/sites/fitness/facilities/' }, { label: 'Üyelik', href: '/sites/fitness/memberships/' }, { label: 'Takvim', href: '/sites/fitness/schedule/' }],
};

function InquiryForm({ mode }: { mode: 'legal' | 'medical' | 'membership' | 'pilot' }) {
  const [sent, setSent] = useState(false);
  const labels = { legal: ['Ön görüşme talebi', 'Konu ve tarafları kısaca belirtin'], medical: ['Muayene talebi', 'Şikâyetinizi ve uygun günleri belirtin'], membership: ['Tanışma seansı', 'Hedefinizi ve antrenman geçmişinizi yazın'], pilot: ['Pilot çalışma', 'Ekip ve günlük operasyon hacminizi yazın'] } as const;
  if (sent) return <div className="form-confirmation"><Check size={22} /><h2>Talebiniz kaydedildi</h2><p>Bu demo akışında veri gönderilmedi. Gerçek projede kayıt CRM sistemine aktarılır.</p></div>;
  return <form className="inquiry-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><h2>{labels[mode][0]}</h2><label>Ad soyad<input required name="name" /></label><label>E-posta<input required type="email" name="email" /></label><label>{labels[mode][1]}<textarea required rows={5} name="note" /></label><Button type="submit">Talebi oluştur</Button></form>;
}

function LawPages({ page, itemSlug }: { page: string; itemSlug?: string }) {
  const data = lawFirmData;
  if (itemSlug) {
    const practice = data.practiceAreas.find((item) => item.slug === itemSlug);
    const publication = data.publications.find((item) => item.slug === itemSlug);
    if (practice) return <section className="container section-block"><Link className="back-link" href="/sites/law/practices/"><ArrowLeft size={16} /> Uzmanlıklara dön</Link><DetailPanel title={practice.title} description={practice.detailedOverview} meta={[{ key: 'Çalışma kapsamı', value: `${practice.scopeOfWork.length} başlık` }, { key: 'Sektörler', value: practice.sectorsServed.join(', ') }]}><h2>Çalışma kapsamı</h2><ul>{practice.scopeOfWork.map((item) => <li key={item}>{item}</li>)}</ul><h2>Mevzuat çerçevesi</h2><ul>{practice.regulatoryFramework.map((item) => <li key={item}>{item}</li>)}</ul></DetailPanel></section>;
    if (publication) return <article className="container section-block editorial-copy"><Link className="back-link" href="/sites/law/publications/"><ArrowLeft size={16} /> Yayınlara dön</Link><p className="section-heading__eyebrow">{publication.category} · {publication.readTimeMinutes} dk.</p><h1>{publication.title}</h1><p className="lead">{publication.excerpt}</p>{publication.content.map((paragraph) => <p key={paragraph.slice(0, 32)}>{paragraph}</p>)}<aside className="legal-note">Bu yayın yalnız genel bilgilendirme amaçlıdır; hukuki görüş değildir.</aside></article>;
  }
  if (page === 'practices') return <section className="container section-block"><SectionHeading eyebrow="10 çalışma alanı" title="İşlemin hukuki mimarisi" body="Her ekip, sektör mevzuatı ile ticari hedefi aynı dosyada birlikte okur." /><ItemGrid columns={3}>{data.practiceAreas.map((item) => <Card key={item.slug} title={item.title} meta={item.sectorsServed.slice(0, 2).join(' · ')} description={item.summary} href={`/sites/law/detail/${item.slug}/`} />)}</ItemGrid></section>;
  if (page === 'team') return <section className="container section-block"><SectionHeading eyebrow="9 hukukçu" title="Dosyanın başında görünen ekip" /><ItemGrid columns={3}>{data.teamMembers.map((member) => <Card key={member.slug} title={member.name} meta={member.seniority} description={`${member.biography} Diller: ${member.languages.join(', ')}.`} image={member.imageUrl} imageAlt={member.imageAlt} />)}</ItemGrid></section>;
  if (page === 'publications') return <section className="container section-block"><SectionHeading eyebrow="Hukuki bülten" title="Mevzuatı karar anına çevirmek" /><div className="article-list">{data.publications.map((item) => <Link key={item.slug} href={`/sites/law/detail/${item.slug}/`}><span>{item.publishedAt}</span><div><h2>{item.title}</h2><p>{item.excerpt}</p></div><ArrowRight size={18} /></Link>)}</div></section>;
  if (page === 'contact') return <section className="container section-block editorial-two-col"><div><SectionHeading eyebrow="Çıkar çatışması kontrolü" title="İlk temas ve ofisler" body={data.brand.regulatoryDisclaimer} />{data.offices.map((office) => <address key={office.city}><strong>{office.name}</strong><br />{office.addressLine1}<br />{office.telephone}<br />{office.email}</address>)}</div><InquiryForm mode="legal" /></section>;
  return <><section className="sector-hero sector-hero--law"><div className="container"><Scale size={28} /><p className="section-heading__eyebrow">{data.brand.headquarters} · {data.brand.foundingYear}</p><h1>{data.brand.heroHeadline}</h1><p>{data.brand.heroSubheadline}</p><Button href="/sites/law/practices/">Uzmanlıkları incele</Button></div></section><section className="container section-block"><StatStrip stats={data.brand.stats.map((item) => ({ value: item.value, label: item.label }))} /><p className="legal-note">{data.brand.regulatoryDisclaimer}</p></section></>;
}

function SaasPages({ page, itemSlug }: { page: string; itemSlug?: string }) {
  const data = saasPlatformData;
  if (itemSlug) { const module = data.modules.find((item) => item.slug === itemSlug); const useCase = data.useCases.find((item) => item.slug === itemSlug); const item = module ?? useCase; if (item && 'capabilities' in item) return <section className="container section-block"><Link className="back-link" href="/sites/saas/product/"><ArrowLeft size={16} /> Ürüne dön</Link><DetailPanel title={item.name} description={item.architectureDetails} image={item.screenshotUrl} imageAlt={item.screenshotAlt} meta={[{ key: item.metricsImpact.label, value: item.metricsImpact.value }, { key: 'Gecikme', value: item.technicalSpecs.latency }, { key: 'Uyumluluk', value: item.technicalSpecs.compliance }]}><ul>{item.capabilities.map((capability) => <li key={capability}>{capability}</li>)}</ul></DetailPanel></section>; if (useCase) return <section className="container section-block"><DetailPanel title={useCase.title} description={useCase.challenge} image={useCase.featuredImageUrl} imageAlt={useCase.featuredImageAlt}><h2>Çözüm akışı</h2><p>{useCase.solution}</p><ul>{useCase.keyWorkflows.map((item) => <li key={item}>{item}</li>)}</ul></DetailPanel></section>; }
  if (page === 'product') return <section className="container section-block"><SectionHeading eyebrow="Ürün mimarisi" title="Operasyonun altı çalışan modülü" /><ItemGrid columns={3}>{data.modules.map((item) => <Card key={item.slug} title={item.name} meta={item.metricsImpact.value} description={item.shortDescription} image={item.screenshotUrl} imageAlt={item.screenshotAlt} href={`/sites/saas/detail/${item.slug}/`} />)}</ItemGrid></section>;
  if (page === 'solutions') return <section className="container section-block"><SectionHeading eyebrow="8 sektör akışı" title="Sahayı olduğu gibi modelleyen çözümler" /><ItemGrid columns={2}>{data.useCases.map((item) => <Card key={item.slug} title={item.title} meta={item.industry} description={item.operationalOutcome} image={item.featuredImageUrl} imageAlt={item.featuredImageAlt} href={`/sites/saas/detail/${item.slug}/`} />)}</ItemGrid></section>;
  if (page === 'pricing') return <section className="container section-block"><SectionHeading eyebrow="Fiyatlandırma" title="Pilot ekipten izole kümeye" /><ItemGrid columns={4}>{data.pricingTiers.map((tier) => <article className="pricing-panel" key={tier.id}><p className="section-heading__eyebrow">{tier.targetScale}</p><h2>{tier.name}</h2><strong>{tier.isCustomQuote ? 'Özel teklif' : `${tier.monthlyPriceTRY?.toLocaleString('tr-TR')} ₺ / ay`}</strong><p>{tier.tagline}</p><ul>{tier.featureHighlights.map((item) => <li key={item}><Check size={14} />{item}</li>)}</ul><Button variant={tier.isPopular ? 'primary' : 'outline'}>{tier.ctaText}</Button></article>)}</ItemGrid></section>;
  if (page === 'changelog') return <section className="container section-block"><SectionHeading eyebrow="16 sürüm" title="Değişiklik günlüğü" /><div className="timeline-list">{data.changelog.map((entry) => <article key={entry.slug}><span>{entry.version}<br />{entry.releaseDate}</span><div><h2>{entry.title}</h2><p>{entry.summary}</p><ul>{entry.highlights.map((item) => <li key={item}>{item}</li>)}</ul></div></article>)}</div></section>;
  if (page === 'docs') return <section className="container section-block"><SectionHeading eyebrow="Teknik dokümantasyon" title="Entegrasyona açık bir operasyon çekirdeği" /><div className="docs-grid">{data.docsNavigation.map((section) => <section key={section.sectionSlug}><h2>{section.sectionTitle}</h2><p>{section.description}</p>{section.items.map((item) => <article key={item.slug}><Code2 size={16} /><div><h3>{item.title}</h3><p>{item.description} · {item.readTime}</p></div></article>)}</section>)}</div></section>;
  return <><section className="sector-hero sector-hero--saas"><div className="container"><Code2 size={28} /><p className="section-heading__eyebrow">B2B operasyon sistemi</p><h1>{data.brand.heroHeadline}</h1><p>{data.brand.heroSubheadline}</p><div className="hero-actions"><Button href="/sites/saas/product/">Ürünü incele</Button><Button href="/sites/saas/docs/" variant="outline">Dokümanlar</Button></div></div></section><section className="container section-block"><StatStrip stats={data.brand.stats.map((item) => ({ value: item.value, label: item.label }))} /><InquiryForm mode="pilot" /></section></>;
}

function DentalPages({ page, itemSlug }: { page: string; itemSlug?: string }) {
  const data = dentalClinicData;
  if (itemSlug) { const treatment = data.treatments.find((item) => item.slug === itemSlug); if (treatment) return <section className="container section-block"><Link className="back-link" href="/sites/dental/treatments/"><ArrowLeft size={16} /> Tedavilere dön</Link><DetailPanel title={treatment.name} description={treatment.fullOverview} image={treatment.imageUrl} imageAlt={treatment.imageAlt} meta={[{ key: 'Seans', value: treatment.expectedSessions }, { key: 'Süre', value: treatment.durationPerSession }, { key: 'Anestezi', value: treatment.anesthesiaType }, { key: 'İyileşme', value: treatment.recoveryTimeline }]}><h2>Klinik süreç</h2><ol>{treatment.clinicalProcess.map((step) => <li key={step.step}><strong>{step.title}</strong><p>{step.detail}</p></li>)}</ol></DetailPanel></section>; }
  if (page === 'treatments') return <section className="container section-block"><SectionHeading eyebrow="14 protokol" title="Fonksiyon ve dokuyu birlikte koruyan tedaviler" /><ItemGrid columns={3}>{data.treatments.map((item) => <Card key={item.slug} title={item.name} meta={item.category} description={item.shortDescription} image={item.imageUrl} imageAlt={item.imageAlt} href={`/sites/dental/detail/${item.slug}/`} />)}</ItemGrid></section>;
  if (page === 'clinicians') return <section className="container section-block"><SectionHeading eyebrow="7 uzman hekim" title="Disiplinler arası klinik kurul" /><ItemGrid columns={3}>{data.clinicians.map((item) => <Card key={item.slug} title={item.name} meta={item.specialty} description={item.biography} image={item.avatarUrl} imageAlt={item.avatarAlt} />)}</ItemGrid></section>;
  if (page === 'technology') return <section className="container section-block"><SectionHeading eyebrow="Dijital klinik" title="Ölçüm, büyütme ve sterilizasyon zinciri" /><ItemGrid columns={3}>{data.technologies.map((item) => <Card key={item.slug} title={item.name} meta={`${item.manufacturer} · ${item.model}`} description={`${item.clinicalAdvantage} ${item.patientBenefit}`} image={item.imageUrl} imageAlt={item.imageAlt} />)}</ItemGrid></section>;
  if (page === 'patient-guide') return <section className="container section-block"><SectionHeading eyebrow="Hasta rehberi" title="Randevu öncesi ve sonrası net bilgi" /><div className="article-list">{data.patientGuides.map((item) => <article key={item.slug}><span>{item.readTime}</span><div><h2>{item.title}</h2><p>{item.summary}</p><ul>{item.criticalRules.map((rule) => <li key={rule}>{rule}</li>)}</ul></div></article>)}</div><p className="medical-note">Bu içerik genel bilgilendirme içindir; muayene ve kişisel tedavi planının yerini tutmaz.</p></section>;
  return <><section className="sector-hero sector-hero--dental"><div className="container"><Stethoscope size={28} /><p className="section-heading__eyebrow">Ruhsatlı özel poliklinik</p><h1>{data.brand.heroHeadline}</h1><p>{data.brand.heroSubheadline}</p><Button href="/sites/dental/treatments/">Tedavileri incele</Button></div></section><section className="container section-block editorial-two-col"><div><StatStrip stats={data.brand.keyStats.map((item) => ({ value: item.value, label: item.label }))} /><p className="medical-note">Tanı ve tedavi yalnız hekim muayenesi sonrası planlanır.</p></div><InquiryForm mode="medical" /></section></>;
}

function FitnessPages({ page, itemSlug }: { page: string; itemSlug?: string }) {
  const data = fitnessClubData;
  if (itemSlug) { const program = data.programs.find((item) => item.slug === itemSlug); if (program) return <section className="container section-block"><Link className="back-link" href="/sites/fitness/programs/"><ArrowLeft size={16} /> Programlara dön</Link><DetailPanel title={program.title} description={program.trainingMethodology} image={program.imageUrl} imageAlt={program.imageAlt} meta={[{ key: 'Seviye', value: program.level }, { key: 'Süre', value: `${program.durationMinutes} dk.` }, { key: 'Kontenjan', value: `${program.classCapacity} kişi` }, { key: 'Yoğunluk', value: `${program.intensityRating}/5` }]}><h2>Hedef adaptasyonlar</h2><ul>{program.targetAdaptations.map((item) => <li key={item}>{item}</li>)}</ul></DetailPanel></section>; }
  if (page === 'programs') return <section className="container section-block"><SectionHeading eyebrow="16 program" title="Ter değil, ölçülebilir adaptasyon" /><ItemGrid columns={3}>{data.programs.map((item) => <Card key={item.slug} title={item.title} meta={`${item.category} · ${item.level}`} description={item.overview} image={item.imageUrl} imageAlt={item.imageAlt} href={`/sites/fitness/detail/${item.slug}/`} />)}</ItemGrid></section>;
  if (page === 'coaches') return <section className="container section-block"><SectionHeading eyebrow="10 koç" title="Programı uygulayan değil, yöneten ekip" /><ItemGrid columns={3}>{data.coaches.map((item) => <Card key={item.slug} title={item.name} meta={item.specialization} description={item.coachingPhilosophy} image={item.avatarUrl} imageAlt={item.avatarAlt} />)}</ItemGrid></section>;
  if (page === 'facilities') return <section className="container section-block"><SectionHeading eyebrow="Performans kampüsü" title="Her metrekarenin bir antrenman amacı var" /><ItemGrid columns={3}>{data.facilities.map((item) => <Card key={item.slug} title={item.name} meta={`${item.areaSquareMeters} m²`} description={item.description} image={item.imageUrl} imageAlt={item.imageAlt} />)}</ItemGrid></section>;
  if (page === 'memberships') return <section className="container section-block"><SectionHeading eyebrow="Üyelik" title="Takvim ve hedefe göre dört erişim biçimi" /><ItemGrid columns={4}>{data.memberships.map((tier) => <article className="pricing-panel" key={tier.id}><h2>{tier.name}</h2><strong>{tier.priceTRY ? `${tier.priceTRY.toLocaleString('tr-TR')} ₺` : 'Kurumsal teklif'}</strong><p>{tier.targetAudience}</p><ul>{tier.inclusions.map((item) => <li key={item}><Check size={14} />{item}</li>)}</ul><Button>{tier.ctaText}</Button></article>)}</ItemGrid></section>;
  if (page === 'schedule') return <section className="container section-block"><SectionHeading eyebrow="Haftalık akış" title="Stüdyo takvimi" /><div className="schedule-table">{data.weeklySchedule.map((slot) => { const program = data.programs.find((item) => item.slug === slot.programSlug); const coach = data.coaches.find((item) => item.slug === slot.coachSlug); return <article key={slot.id}><strong>{slot.dayOfWeek}</strong><span>{slot.startTime}–{slot.endTime}</span><div><h2>{program?.title}</h2><p>{coach?.name} · {slot.intensity}</p></div><em>{slot.spotsAvailable} yer</em></article>; })}</div></section>;
  return <><section className="sector-hero sector-hero--fitness"><div className="container"><Dumbbell size={28} /><p className="section-heading__eyebrow">Etiler + Maslak</p><h1>{data.brand.heroHeadline}</h1><p>{data.brand.heroSubheadline}</p><Button href="/sites/fitness/programs/">Programları gör</Button></div></section><section className="container section-block editorial-two-col"><div><StatStrip stats={data.brand.stats.map((item) => ({ value: item.value, label: item.label }))} /></div><InquiryForm mode="membership" /></section></>;
}

export function ServicesRenderer({ siteId, pageSlug, itemSlug }: { siteId: SiteId; pageSlug: string; itemSlug?: string }) {
  const brands = { law: lawFirmData.brand.name, saas: saasPlatformData.brand.name, dental: dentalClinicData.brand.name, fitness: fitnessClubData.brand.name };
  const taglines = { law: lawFirmData.brand.tagline, saas: saasPlatformData.brand.tagline, dental: dentalClinicData.brand.tagline, fitness: fitnessClubData.brand.tagline };
  const content = siteId === 'law' ? <LawPages page={pageSlug} itemSlug={itemSlug} /> : siteId === 'saas' ? <SaasPages page={pageSlug} itemSlug={itemSlug} /> : siteId === 'dental' ? <DentalPages page={pageSlug} itemSlug={itemSlug} /> : <FitnessPages page={pageSlug} itemSlug={itemSlug} />;
  return <SiteShell brand={brands[siteId]} tagline={taglines[siteId]} nav={NAV[siteId]} theme={siteId}>{content}</SiteShell>;
}
